### PR TITLE
Convert to a Pimple ServiceProvider

### PR DESCRIPTION
**Pull request by rmasters**
Makes this service provider accessible on any Pimple-based app - Silex, Cilex, etc.

I'm 90% sure this is right (it works in Silex/Cilex at least) - would like someone to confirm though.

### CODE REVIEW

**Comment by jmleroux** [comment]
A similar Pimple Service Provider exists : https://github.com/Cilex/console-service-provider

**Comment by flip111** [comment]
duplicate of https://github.com/KnpLabs/ConsoleServiceProvider/pull/8

**Comment by silverpark** [comment]
Hi,

Where are changes on master branch ?

I need merge this please without fork

Regards,

**Comment by flip111** [comment]
@silverpark this repo seems not maintained anymore. Perhaps try this https://github.com/Cilex/console-service-provider

**Comment by silverpark** [comment]
Thank you very much ;)

**Comment by CrimsonLabs** [comment]
I think we can close this now

**Comment by flip111** [comment]
@CrimsonLabs if you want this provider to stay @ silex 1.* and slowly die yes. https://github.com/Cilex/console-service-provider will probably serve for silex 2.0 projects. Normally it's better to have some healthy package competition though :) Why not make a tag like suggested by @Nek- ?

**Comment by CrimsonLabs** [comment]
No worries - I'm going to work on a split in the next few days.

**Comment by CrimsonLabs** [comment]
Please see version 2.0, this resolves the issue.

**Pull request closed without merging**
