### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by CrimsonLabs**
Change maintainer as per Ryan

### CODE REVIEW

**Comment by weaverryan** [comment]
Awesome - thanks!

**Comment by CrimsonLabs** [comment]
@weaverryan Please would you update Packagist to no longer show the project as abaondoned?

**Comment by weaverryan** [comment]
@CrimsonLabs I don't have the power, but I just asked @ubermuda https://twitter.com/weaverryan/status/734439901249318912

**Comment by CrimsonLabs** [comment]
Awesome, thanks! @weaverryan

**Comment by ubermuda** [comment]
All done!

**Comment by CrimsonLabs** [comment]
Thanks!

Kind Regards,
*Marc*

**Pull request merged**
