### PR TITLE
Fixed bug: boot the Application when run has executed

### PR DESCRIPTION
**Pull request by liuggio**
The problem is that if you boot the silex application in the constructor
some other providers won't work

### CODE REVIEW

**Comment by weaverryan** [comment]
Hey @liuggio!

I think this repo may not be maintained at all anymore - no commits for 2 years. I've never used this myself - I just didn't want your PR to go without at least some attention (even if my comment isn't very helpful!)

**Comment by CrimsonLabs** [comment]
This seems correct to me, and works as intended.

**Comment by weaverryan** [comment]
I agree. But what if a Command accesses calls the `getSilexApplication` from inside `configure()`? Will the app be booted by then with this method?

**Comment by CrimsonLabs** [comment]
Yeah - good point!

**Pull request closed without merging**
