### PR TITLE
Silex 2.* update

### PR DESCRIPTION
**Pull request by flip111**
Makes ConsoleServiceProvider compatible with Silex 2.*

### CODE REVIEW

**Comment by CrimsonLabs** [comment]
@flip111 is this backwards compatible?

**Comment by flip111** [comment]
Pretty sure it's not.

Other Silex provider packages which i saw had to release an explicit version for silex 2.0

**Comment by CrimsonLabs** [comment]
Good Idea - thanks @flip111 I'll be looking into this.

**Comment by CrimsonLabs** [comment]
@weaverryan Do you think we still need to support silex 1.*?

**Comment by CrimsonLabs** [comment]
This works 100% correctly in Silex 2. It has my vote.

**Comment by lplume** [comment]
great news! Thanks @flip111 about the patch
@CrimsonLabs lets us know about the version. Nice works guys!

**Pull request merged**
